// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL-NWFK8xYAwdpzIViUNFNetxan7cAVDU',
    appId: '1:224937379373:web:ff8062bcc163a26f475aa4',
    messagingSenderId: '224937379373',
    projectId: 'flow-7049f',
    authDomain: 'flow-7049f.firebaseapp.com',
    storageBucket: 'flow-7049f.firebasestorage.app',
    measurementId: 'G-QMPG7ZDX40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq8IWTbKIiZYzxM-r4TaMntGt9NgT3MsU',
    appId: '1:224937379373:android:d2376ab705ca8b74475aa4',
    messagingSenderId: '224937379373',
    projectId: 'flow-7049f',
    storageBucket: 'flow-7049f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj5On3OMXeE3CJpPlOxQ7e8JkrRr7Bq3Q',
    appId: '1:224937379373:ios:dffdc39ce487ca66475aa4',
    messagingSenderId: '224937379373',
    projectId: 'flow-7049f',
    storageBucket: 'flow-7049f.firebasestorage.app',
    iosBundleId: 'com.example.flow',
  );
}
